from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('contas/', views.contas, name='contas'),
    path('transacoes/', views.transacoes, name='transacoes'),
    path('metas/', views.metas, name='metas'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('relatorios/', views.relatorios, name='relatorios'),
    path('logs/', views.logs, name='logs'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('backup/', views.backup, name='backup'),
    path('extratos/', views.extratos, name='extratos'),
    path('transferencias/', views.transferencias, name='transferencias'),
    path('admin-backup/', views.admin_backup, name='admin_backup'),
    path('admin-reports/', views.admin_reports, name='admin_reports'),
    path('admin-reset/', views.admin_reset, name='admin_reset'),
    path('admin-users/', views.admin_users, name='admin_users'),
    path('debug-database/', views.debug_database, name='debug_database'),
    path('debug-login-mark3/', views.debug_login_mark3, name='debug_login_mark3'),
    path('diagnose-mark3/', views.diagnose_mark3, name='diagnose_mark3'),
    path('force-restore-mark3/', views.force_restore_mark3, name='force_restore_mark3'),
    path('reset-mark3-teste/', views.reset_mark3_teste, name='reset_mark3_teste'),
    path('restore-manual-mark3/', views.restore_manual_mark3, name='restore_manual_mark3'),
    path('restore-mark3-manual/', views.restore_mark3_manual, name='restore_mark3_manual'),
    path('restore-mark3-teste/', views.restore_mark3_teste, name='restore_mark3_teste'),
    path('restore-simples-mark3/', views.restore_simples_mark3, name='restore_simples_mark3'),
    path('status/', views.status, name='status'),
    path('verificacao-completa/', views.verificacao_completa, name='verificacao_completa'),
    path('verificacao-final/', views.verificacao_final, name='verificacao_final'),
]
